[package]
name = "pros-devices"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pros-core = { version = "0.1.0", path = "../pros-core" }
pros-sys = { path = "../pros-sys", version = "0.6.0", features = ["xapi"] }
snafu = { version = "0.8.0", default-features = false, features = [
    "rust_1_61",
    "unstable-core-error",
] }
no_std_io = { version = "0.6.0", features = ["alloc"] }
