[package]
name = "pros-devices"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "High level device for pros-rs"
keywords = ["PROS", "Robotics", "bindings", "vex", "v5"]
categories = [
    "api-bindings",
    "no-std",
    "science::robotics",
]
repository = "https://github.com/gavin-niederman/pros-rs"
authors = [
    "pros-rs",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pros-core = { version = "0.1.0", path = "../pros-core" }
pros-sys = { path = "../pros-sys", version = "0.7.0", features = ["xapi"] }
snafu = { version = "0.8.0", default-features = false, features = [
    "rust_1_61",
    "unstable-core-error",
] }
no_std_io = { version = "0.6.0", features = ["alloc"] }

[lints]
workspace = true
