[package]
name = "pros-async"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A simple async executor for pros-rs"
keywords = ["PROS", "Robotics", "bindings", "async", "vex", "v5"]
categories = [
    "no-std",
    "science::robotics",
    "Asynchronous"
]
repository = "https://github.com/gavin-niederman/pros-rs"
authors = [
    "pros-rs",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-task = { version = "4.5.0", default-features = false }
pros-core = { version = "0.1.0", path = "../pros-core" }
waker-fn = "1.1.1"
pros-sys = { version = "0.7.0", path = "../pros-sys" }

[lints]
workspace = true
