[package]
name = "pros-panic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pros-core = { version = "0.1.0", path = "../pros-core" }
pros-devices = { version = "0.1.0", path = "../pros-devices", optional = true }
pros-sys = { version = "0.6.0", path = "../pros-sys" }
pros-sync = { version = "0.1.0", path = "../pros-sync" }

[features]
default = ["display_panics"]

display_panics = ["dep:pros-devices"]
