[package]
name = "pros"
version = "0.8.0"
edition = "2021"
description = "Rust bindings for PROS"
keywords = ["PROS", "Robotics", "bindings", "vex", "v5"]
categories = ["os", "api-bindings", "no-std", "science::robotics"]
license = "MIT"
repository = "https://github.com/pros-rs/pros-rs"
readme = "../../README.md"
authors = [
    "pros-rs",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
]
rust-version = "1.75.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pros-sync = { version = "0.1.0", path = "../pros-sync", optional = true }
pros-async = { version = "0.1.0", path = "../pros-async", optional = true }
pros-devices = { version = "0.1.0", path = "../pros-devices", optional = true }
pros-panic = { version = "0.1.0", path = "../pros-panic", optional = true }
pros-core = { version = "0.1.0", path = "../pros-core", optional = true }
pros-math = { version = "0.1.0", path = "../pros-math", optional = true }
pros-sys = { version = "0.7.0", path = "../pros-sys" }

[features]
default = ["async", "devices", "panic", "display_panics", "core", "math"]

core = ["dep:pros-core"]

async = ["dep:pros-async"]
sync = ["dep:pros-sync"]

devices = ["dep:pros-devices"]

math = ["dep:pros-math"]

panic = ["dep:pros-panic"]
display_panics = ["pros-panic/display_panics"]
