[package]
name = "vex-panic"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Panic handler for vex-rs"
keywords = ["PROS", "Robotics", "vex", "v5"]
categories = [
    "no-std",
    "science::robotics",
]
repository = "https://github.com/pros-rs/vex-rs"
authors = [
    "pros-rs",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vex-core = { version = "0.1.0", path = "../vex-core" }
vex-devices = { version = "0.1.0", path = "../vex-devices", optional = true }
pros-sys = { version = "0.7.0", path = "../pros-sys" }

[features]
default = ["display_panics"]

display_panics = ["dep:vex-devices"]

[lints]
workspace = true
