[package]
name = "pros-graphics"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Core functionality for pros-rs"
keywords = ["PROS", "Robotics", "graphics", "vex", "v5"]
categories = [
    "api-bindings",
    "no-std",
    "science::robotics",
]

[dependencies]
embedded-graphics-core = { version = "0.4.0", optional = true }
pros-devices = { version = "0.1.0", path = "../pros-devices" }
pros-sys = { version = "0.7.0", path = "../pros-sys" }

[lints]
workspace = true

[features]
default = []
embedded-graphics = ["dep:embedded-graphics-core"]
