[package]
name = "pros-math"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Commonly used mathematical formulas for pros-rs"
keywords = ["PROS", "Robotics", "vex", "v5"]
categories = [
    "no-std",
    "science::robotics",
    "Mathematics",
]
repository = "https://github.com/gavin-niederman/pros-rs"
authors = [
    "pros-rs",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
]

[dependencies]
num = { version = "0.4.1", default-features = false }
pros-core = { version = "0.1.0", path = "../pros-core" }

[lints]
workspace = true
