[package]
name = "pros-sys"
version = "0.7.0"
edition = "2021"
description = "EFI for the PROS rust bindings"
keywords = ["PROS", "Robotics", "bindings", "vex", "v5"]
categories = [
    "api-bindings",
    "development-tools::ffi",
    "external-ffi-bindings",
    "no-std",
    "science::robotics",
]
license = "MIT"
repository = "https://github.com/gavin-niederman/pros-rs"
links = "pros"

[lib]
doctest = false

[features]
xapi = []
no-link = []

[build-dependencies]
cfg-if = "1.0"

[dependencies]
cfg-if = "1.0"
