[package]
name = "vex-sync"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "`SyncRobot` trait and macro for pros-rs"
keywords = ["PROS", "Robotics", "vex", "v5"]
categories = [
    "no-std",
    "science::robotics",
]
repository = "https://github.com/pros-rs/vex-rs"
authors = [
    "pros-rs",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vex-core = { version = "0.1.0", path = "../vex-core" }

[lints]
workspace = true
